### ISSUE TITLE
Setting Folder attribute

### ISSUE THREAD

**Issue by bikeridercz** [vgrem/Office365-REST-Python-Client#477]
Dear Friend, thank you very much for your work. We are using your python API to create a folder on SPO.  We defined a few custom attributer on folder level in manual way. MS is calling those attributes as a Columns. We need to set values to those attributes immediatelly after creating a new folder via your API. Let me please know if it is possible and how. Thank you. Radim

**Comment by vgrem** [comment]
Greetings,

this is supported although i tend to agree not that much intuitive from API perspective, arguably the main confusion is caused by the fact that folder properties are specified via _associated_ `ListItem` for a folder instead of `Folder` resource.     

Anyway here are the steps involved when folder properties needs to be set:

- folders gets created via `Folder.add(name)` method
- the _associated_ list item for a folder  is addressed via `Folder.list_item_all_fields` property
- and finally folder properties are set via list item: `folder_item.set_property(field_name, field_value).update()` 
 

Here is an example:

```python
ctx = ClientContext(site_url).with_credentials(credentials)

# 1.create a folder 
target_folder = ctx.web.default_document_library().root_folder.add(folder_name).execute_query()
# 2. get assiciated folder  listitem 
folder_item = target_folder.list_item_all_fields
# 3. set folder properties
folder_item.set_property(field_name, field_value).update().execute_query()
```

**Comment by bikeridercz** [comment]
Thank you very much, yes that worked ...

However it seems, that there are some restrictions using **field_name**. When a field name contains simple ASCII characters (example field_name='TicketId') it work fine, when using national characters (field_name='Řešitel') then I'getting errors ... I wasn't able to workaround it in any way.

Finally I have a question, is there a way how to retrieve a value from field_name ? Something like value=folder_item.get_property(field_name).execute_query() ?

Thanks for answer to both questions.

**Comment by bikeridercz** [comment]
So, getting properties now work for me:
...
fields.get().execute_query()
ticketType = fields.get_property('TicketType','')
...

However the problem with national characters still persists. Thanks for help.

**Comment by vgrem** [comment]
Greetings,

regarding:

 
> When a field name contains simple ASCII characters (example field_name='TicketId') it work fine, when using national characters (field_name='Řešitel') then I'getting errors

the error occurs since `set_property` method expects field **internal name**. It is relevant to distinct when addressing field by name in SharePoint API since:   

- **display name** refers to name that was given to a column when it was created, and it is the name that is shown to end user 

- **internal name** is obtained from display name but all special characters and spaces are replaced with Unicode.


In your case `Řešitel` refers to field display name which most likely differs from field internal name.

**Comment by bikeridercz** [comment]
There is a simple workaround hot to use international characters in field names without encoding/decoding it in complicated manner:
1. create field name in a simple way just with ASCII characters without special chars like space etc. (example: "**Responsible**")
2. then edit this name to the target one (example: "**Řešitel požadavku**")

Then, original name ("**Responsible**") remains set as **Internal field name** and is used as a reference in API calls. The "**Řešitel požadavku**" is set as **Display name** and is used just for displaying.
